print("What is your name human?")
name = input()
print("How old are you?")
age = str(input())
print("How tall are you?")
height = float(input())
print("How much do you weight in kilograms?")
mass = str(input())
print("Welcome {}. you are {} years old. Your height is {} and you weight {}".format(name,age,height,mass))