print("Please enter the numer of lives.")
number_lives =int(input())
print("Please enter the energy level.")
energy = int(input())
print("Health has been set")
print("Lives:" +"\u270A"*3)
print("Energy:" + "\u272d"*5)
print("Shield:" + "\u2730"*7)